[build]
  command = "npm run build -- --configuration=production"
  publish = "dist/parlor/browser"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/angular-runtime"